"""Constantes do domínio Componentes Curriculares."""

CODIGO_COMPONENTE_REGENCIA_CLASSE_INFANTIL = 512
DESCRICAO_COMPONENTE_REGENCIA_CLASSE_INFANTIL = "Regência de classe infantil"

MOTIVO_DISPONIBILIZACAO_FIM_ANO_LETIVO = 34

TIPO_TURMA_REGULAR = 1
TIPO_TURMA_ED_FISICA = 2
TIPO_TURMA_PROGRAMA = 3
TIPO_TURMA_EVENTO_PARA_ATRIBUICAO = 4
TIPO_TURMA_CLASSE_BILINGUE_II = 5
TIPO_TURMA_ITINERARIO_ENSINO_MEDIO = 6
TIPO_TURMA_ITINERARIOS_2A_ANO = 7
