"""Constantes do domínio Componentes Curriculares."""

TIPO_TURMA_REGULAR = 1
TIPO_TURMA_ED_FISICA = 2
TIPO_TURMA_PROGRAMA = 3
TIPO_TURMA_EVENTO_PARA_ATRIBUICAO = 4
TIPO_TURMA_CLASSE_BILINGUE_II = 5
TIPO_TURMA_ITINERARIO_ENSINO_MEDIO = 6
TIPO_TURMA_ITINERARIOS_2A_ANO = 7
