"""Constantes do domínio Turmas."""

MENSAGEM_COMPORTAMENTO_INESPERADO = (
    "Houve um comportamento inesperado do sistema. "
    "Por favor, contate a SME."
)

ETAPA_ENSINO_MAGISTERIO = 9
TIPO_GRADE_PROGRAMA_ITINERARIO = 23

TIPOS_ESCOLA_TURMAS_HISTORICAS_PROFESSOR = (1, 2, 3, 4, 16, 28, 31)
ETAPAS_ENSINO_TURMAS_HISTORICAS_PROFESSOR = (
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    10,
    11,
    12,
    13,
    14,
    17,
)

CODIGO_GRADE_PROGRAMA_LINGUAGENS = 5148
CODIGO_GRADE_PROGRAMA_HUMANAS_SOCIAIS = 5149
CODIGO_GRADE_PROGRAMA_CIENCIAS_MATEMATICA = 5150

DESCRICOES_GRADE_PROGRAMA_ITINERARIO = {
    CODIGO_GRADE_PROGRAMA_LINGUAGENS: "Linguagens",
    CODIGO_GRADE_PROGRAMA_HUMANAS_SOCIAIS: "Humanas e Sociais",
    CODIGO_GRADE_PROGRAMA_CIENCIAS_MATEMATICA: "Ciências e Matemática",
}
